name: Playwright CI
on:
  push:
    branches: [ master ]
jobs:
  test:
    runs-on: ubuntu-latest # GitHub provides this Linux server for free
    steps:
      - uses: actions/checkout@v4 # Clones your code

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Install Project Dependencies
        run: mvn install -DskipTests

      - name: Install Playwright Browsers
        run: mvn exec:java -e -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run Playwright Tests
        run: mvn test

      - name: Upload Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-report
          path: target/surefire-reports/